import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Orbitron, Playfair_Display } from "next/font/google";
import "./globals.css";
import LenisProvider from "../components/global/lenisProvider";
import AppShell from "@/components/global/AppShell";
import { cn } from "@/lib/utils";

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn("antialiased", geistSans.variable, geistMono.variable, orbitron.variable, playfair.variable, "font-sans", inter.variable)}
    >
      <body suppressHydrationWarning className="relative cursor-none bg-black">
        <LenisProvider>
          <AppShell>
            {children}
          </AppShell>
        </LenisProvider>
      </body>
    </html>
  );
}
